CREATE TABLE IF NOT EXISTS marketing_bi_portfolio_box_score_rows (
  id TEXT PRIMARY KEY,
  report_date TEXT NOT NULL,
  property_name TEXT NOT NULL,
  property_id TEXT,
  community_id TEXT,
  units INTEGER,
  physical_occupancy_pct REAL,
  occupancy_30_pct REAL,
  occupancy_60_pct REAL,
  adjusted_physical_occupancy_pct REAL,
  adjusted_occupancy_30_pct REAL,
  adjusted_occupancy_60_pct REAL,
  current_occupancy_rent REAL,
  net_effective_rent REAL,
  co_vs_ner_pct REAL,
  rent_actual_effective_yoy_pct REAL,
  concession_months_t90 REAL,
  concession_months_91_180 REAL,
  concession_frequency_t90_pct REAL,
  concession_frequency_91_180_pct REAL,
  guest_cards_t30 INTEGER,
  guest_cards_t30_vs_ly_pct REAL,
  guest_cards_t7 INTEGER,
  guest_cards_t7_vs_ly_pct REAL,
  onsite_tours_t30 INTEGER,
  onsite_tours_t30_vs_ly_pct REAL,
  onsite_tours_t7 INTEGER,
  onsite_tours_t7_vs_ly_pct REAL,
  tour_guest_card_t30_pct REAL,
  application_tour_t30_pct REAL,
  application_guest_card_t30_pct REAL,
  lease_application_t30_pct REAL,
  applications INTEGER,
  cancel_denials INTEGER,
  ntv INTEGER,
  coverage INTEGER,
  ready_available INTEGER,
  make_ready_pct REAL,
  turn_time_t30 REAL,
  deferred_t30_pct REAL,
  service_requests_t7 INTEGER,
  service_requests_t7_units_pct REAL,
  kingsley_os_t90_pct REAL,
  kingsley_os_t90_vs_ly_pct REAL,
  kingsley_nps_t90_pct REAL,
  kingsley_nps_t90_vs_ly_pct REAL,
  source_file TEXT NOT NULL,
  evidence_json TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(report_date, property_name, source_file)
);

CREATE INDEX IF NOT EXISTS idx_marketing_bi_box_score_property_date
  ON marketing_bi_portfolio_box_score_rows(property_id, report_date DESC);

CREATE TABLE IF NOT EXISTS marketing_bi_service_delivery_rows (
  id TEXT PRIMARY KEY,
  report_date TEXT NOT NULL,
  property_name TEXT NOT NULL,
  property_id TEXT,
  community_id TEXT,
  no_response_count INTEGER,
  no_response_aging INTEGER,
  unresolved_volume_48h_plus INTEGER,
  first_response_vs_region TEXT,
  first_response INTEGER,
  total_resolution INTEGER,
  reopen_rate_vs_portfolio TEXT,
  ticket_volume_vs_portfolio TEXT,
  source_file TEXT NOT NULL,
  evidence_json TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(report_date, property_name, source_file)
);

CREATE INDEX IF NOT EXISTS idx_marketing_bi_service_delivery_property_date
  ON marketing_bi_service_delivery_rows(property_id, report_date DESC);

CREATE TABLE IF NOT EXISTS marketing_bi_abandoned_application_rows (
  id TEXT PRIMARY KEY,
  report_date TEXT NOT NULL,
  property_name TEXT,
  property_id TEXT,
  community_id TEXT,
  unit_code TEXT,
  count_value INTEGER,
  beds_baths TEXT,
  floorplan_type TEXT,
  total_units INTEGER,
  available_units INTEGER,
  sqft INTEGER,
  applied_date TEXT,
  lease_type TEXT,
  lease_term INTEGER,
  contract_created_date TEXT,
  lease_start_date TEXT,
  expected_move_in_date TEXT,
  lease_end_date TEXT,
  net_rent REAL,
  source_file TEXT NOT NULL,
  row_number INTEGER NOT NULL,
  evidence_json TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(report_date, source_file, row_number)
);

CREATE INDEX IF NOT EXISTS idx_marketing_bi_abandoned_property_date
  ON marketing_bi_abandoned_application_rows(property_id, report_date DESC);
