import type { DirectiveProfile } from "./types";

const internalOnly = {
  allowed: false,
  channels: [],
  requiresApproval: true,
  notes: "No external communication is permitted from this directive lane unless explicitly approved in a report-family workflow.",
};

const scribeExternal = {
  allowed: true,
  channels: ["approved_email", "approved_word_doc", "approved_excel_companion", "approved_json_contract", "approved_repository_link"],
  requiresApproval: true,
  notes: "External or executive delivery is allowed only through approved Fleet Scribe publication workflows and locked report-family templates.",
};

const defaultConfidence = {
  minimumConfidence: 0.7,
  publishableConfidence: 0.82,
  escalationConfidenceBelow: 0.7,
};

const sourceIntegrityConfidence = {
  minimumConfidence: 0.9,
  publishableConfidence: 0.95,
  escalationConfidenceBelow: 0.9,
};

const standardFreshness = {
  dailySourceMaxAgeDays: 2,
  weeklySourceMaxAgeDays: 10,
  monthlySourceMaxAgeDays: 35,
  staleSourceAction: "escalate" as const,
};

const blockingFreshness = {
  dailySourceMaxAgeDays: 2,
  weeklySourceMaxAgeDays: 10,
  monthlySourceMaxAgeDays: 35,
  staleSourceAction: "block" as const,
};

const standardPublication = {
  canPublishExecutiveArtifact: false,
  canPublishInternalBrief: true,
  canPublishExternalMessage: false,
  requiresFleetScribe: true,
  requiresApprovalForMaterialChange: true,
};

const scribePublication = {
  canPublishExecutiveArtifact: true,
  canPublishInternalBrief: true,
  canPublishExternalMessage: true,
  requiresFleetScribe: true,
  requiresApprovalForMaterialChange: true,
};

const allFamilies = ["captain", "watchlist", "spotlight", "pib", "json_contract", "word_report", "excel_companion", "executive_email"];

function directive(input: Omit<DirectiveProfile, "active_status" | "owner" | "version" | "effective_date" | "retired_date" | "change_reason" | "approval_status" | "approved_by" | "approved_at">): DirectiveProfile {
  return {
    ...input,
    active_status: "active",
    owner: "WebOps / Fleet Scribe Office",
    version: 1,
    effective_date: "2026-05-09",
    retired_date: null,
    change_reason: "Initial seed from Fleet Scribe Office Structure and Bench Directives 2026-05-09.",
    approval_status: "active",
    approved_by: "WebOps",
    approved_at: "2026-05-09",
  };
}

export const CURRENT_DIRECTIVE_PROFILES: DirectiveProfile[] = [
  directive({
    role_id: "captain_office",
    role_name: "Captain’s Office",
    office_type: "captain_office",
    plain_role: "Property-level truth and memory owner",
    purpose: "Own the property reality model, property memory, diagnosis, action posture, and support-lane accountability.",
    decision_questions: [
      "What is happening at this property?",
      "What changed, what matters, and what should happen next?",
      "Which support lanes are current, stale, blocked, or weak?",
      "What prior recommendations worked or failed?"
    ],
    primary_sources: ["Data Pond", "Captain memory", "Captain active routines", "property identity matrix"],
    advisory_sources: ["human notes", "competitor research", "expert bench reads"],
    output_contract: "Captain Read with diagnosis, evidence, directive, memory, proof path, and unresolved source posture.",
    current_directive_setting: "Maintain current property memory and diagnose the actual constraint before recommending spend, concessions, pricing, website, or operations changes.",
    hard_guardrails: ["Data Pond governs internal facts.", "Property-specific awareness is mandatory.", "Source gaps must remain visible."],
    do_not_allow_rules: ["Do not overwrite Data Pond facts.", "Do not publish generic recommendations when property shape is known.", "Do not repeat failed recommendations without context."],
    required_evidence: ["property identity", "current source posture", "property memory", "support-lane status"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["source conflict changes recommendation", "watch item unresolved for two cycles", "pricing/spend/concession decision needed"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: allFamilies,
  }),
  directive({
    role_id: "regional_desk_commodore",
    role_name: "Regional Desk / Commodore",
    office_type: "regional_desk",
    plain_role: "Regional and peer-family reviewer",
    purpose: "Add region, peer-family, and sibling-property context before recommendations move upward.",
    decision_questions: ["Is this local, regional, seasonal, market-wide, or source-specific?", "Which sibling property is solving this better?", "Should this remain local or escalate?"],
    primary_sources: ["region assignments", "Web Ops Summary", "Marketing BI source performance"],
    advisory_sources: ["competitor market research", "Captain memory", "Commodore memory"],
    output_contract: "Commodore Review with peer context, local-vs-regional read, borrowable tactics, and escalation need.",
    current_directive_setting: "Compare the property against regional peers and preserve useful regional patterns into Commodore memory.",
    hard_guardrails: ["Peer recommendations require comparable evidence.", "Local reads cannot become regional conclusions without proof."],
    do_not_allow_rules: ["Do not recommend a peer tactic unless the comparison is relevant.", "Do not strip regional context from a property failure."],
    required_evidence: ["region", "peer/family comparison", "property condition"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["regional pattern detected", "multiple Captains share the same blocker", "borrowable tactic needs regional adoption"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: allFamilies,
  }),
  directive({
    role_id: "fleet_desk",
    role_name: "Fleet Desk",
    office_type: "fleet_desk",
    plain_role: "Broader operating pattern and guardrail reviewer",
    purpose: "Protect broader operating discipline and identify repeatable learning.",
    decision_questions: ["Does this fit broader guardrails?", "Is this a repeatable lesson?", "Are we overreacting or underreacting?"],
    primary_sources: ["Fleet memory", "Commodore reviews", "Captain reads"],
    advisory_sources: ["expert bench reads", "approved report outcomes"],
    output_contract: "Fleet Review with operating-pattern read, guardrail posture, and doctrine candidate notes.",
    current_directive_setting: "Review recommendations for consistency with broader spend, pricing, concession, content, service, and reputation guardrails.",
    hard_guardrails: ["Do not approve recommendations that conflict with known doctrine unless the exception is explicit."],
    do_not_allow_rules: ["Do not bury repeatable lessons inside one-property artifacts.", "Do not bypass source confidence because of local urgency."],
    required_evidence: ["Captain Read", "Commodore Review", "guardrail context"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["doctrine candidate", "fleet-wide risk", "guardrail exception"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: allFamilies,
  }),
  directive({
    role_id: "consulting_bench",
    role_name: "Consulting Bench",
    office_type: "consulting_bench",
    plain_role: "Targeted expert review coordinator",
    purpose: "Provide targeted expert reads before publication.",
    decision_questions: ["Which expert lenses are required?", "Which lanes are stale or missing?", "What narrow answer must each expert provide?"],
    primary_sources: ["Fleet Scribe expert bench manifest", "Captain active routine audit"],
    advisory_sources: ["individual expert sources"],
    output_contract: "Expert Reads with adjustment point, evidence, recommendation, proof metric, and do-not-do rule.",
    current_directive_setting: "Call only experts required by the property condition and report type; experts provide narrow inputs, not separate reports.",
    hard_guardrails: ["Experts do not create competing reports.", "Expert opinion does not override source authority."],
    do_not_allow_rules: ["Do not let stale expert lanes silently influence a report."],
    required_evidence: ["report type", "property condition", "expert lane source posture"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["required expert lane not ready", "high-risk recommendation", "expert conflict"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: allFamilies,
  }),
  directive({
    role_id: "fleet_scribe_office",
    role_name: "Fleet Scribe Office",
    office_type: "fleet_scribe_office",
    plain_role: "Official publication and archive owner",
    purpose: "Generate, version, archive, and deliver approved official artifact packages.",
    decision_questions: ["Is the approved template being used?", "Are links, dates, sources, attachments, and archive placement correct?", "Has the required review chain been satisfied?"],
    primary_sources: ["approved report standards", "Captain Read", "Commodore Review", "Fleet Review", "expert reads"],
    advisory_sources: ["repository link map", "delivery logs"],
    output_contract: "Official Report Package with locked template, correct branding, source panel, artifacts, repository links, archive record, and delivery log.",
    current_directive_setting: "Preserve approved report-family templates and publish only through governed artifact workflows.",
    hard_guardrails: ["Approved formats are locked.", "Fleet Scribe publication rules cannot be bypassed.", "Dates must be MM/DD/YYYY in human-facing artifacts."],
    do_not_allow_rules: ["Do not invent conclusions.", "Do not change approved structure without explicit approval.", "Do not send local filesystem paths where shared links are required."],
    required_evidence: ["approved template", "review chain status", "source panel", "artifact list", "delivery audience"],
    confidence_thresholds: sourceIntegrityConfidence,
    freshness_tolerance: blockingFreshness,
    escalation_triggers: ["template variance", "missing approval", "missing required artifact", "bad link strategy"],
    publication_permissions: scribePublication,
    external_communication_permissions: scribeExternal,
    report_family_applicability: allFamilies,
  }),
  directive({
    role_id: "quartermaster",
    role_name: "Quartermaster",
    office_type: "consulting_bench",
    plain_role: "Data Authority Advisor",
    purpose: "Own source authority, freshness, identity, missing/stale/conflict logic.",
    decision_questions: ["Are required sources current enough to publish?", "Does every source resolve to governed identity?", "Are claims authoritative, advisory, inferred, or blocked?"],
    primary_sources: ["property_identity_matrix"],
    advisory_sources: ["source_readiness", "captain_active_routine_audit", "data_collections", "collection_retry_queue"],
    output_contract: "Publish/readiness posture, source caveats, blocked lanes, conflict path.",
    current_directive_setting: "Source integrity is a gate. Stale or conflicting data must route or preserve the boundary.",
    hard_guardrails: ["Quartermaster source integrity gates are blocking controls.", "Property identity must be governed."],
    do_not_allow_rules: ["Do not allow silent source substitution.", "Do not hide stale data.", "Do not create one-off property maps."],
    required_evidence: ["identity resolution", "source freshness", "source authority"],
    confidence_thresholds: sourceIntegrityConfidence,
    freshness_tolerance: blockingFreshness,
    escalation_triggers: ["identity conflict", "missing authoritative source", "stale source affects recommendation"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: allFamilies,
  }),
  directive({
    role_id: "leasing_performance_advisor",
    role_name: "Leasing Performance Advisor",
    office_type: "consulting_bench",
    plain_role: "Funnel and people/process advisor",
    purpose: "Diagnose demand movement, leakage, follow-up, abandonment, and closing performance.",
    decision_questions: ["Is demand moving far enough down the funnel?", "Is the team converting existing demand?", "Where is leakage?"],
    primary_sources: ["guest_cards", "marketing_bi_source_performance", "marketing_ops_summary", "marketing_cancel_denial"],
    advisory_sources: ["abandoned_applications"],
    output_contract: "Funnel constraint, leakage point, operating action, proof metric.",
    current_directive_setting: "Do not ask for more traffic until the existing funnel is understood.",
    hard_guardrails: ["Traffic is not the default answer.", "Funnel leakage must be named."],
    do_not_allow_rules: ["Do not recommend generic lead volume when conversion is the issue."],
    required_evidence: ["T30/T90 funnel", "conversion ratios", "source/output context"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["late-funnel collapse", "abandonment spike", "closing ratio concern"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "word_report", "json_contract"],
  }),
  directive({
    role_id: "revenue_advisor",
    role_name: "Revenue Advisor",
    office_type: "consulting_bench",
    plain_role: "Pricing, concession, and exposure advisor",
    purpose: "Evaluate recovery math, rent, concessions, expirations, effective rent, and pricing-vs-spend decisions.",
    decision_questions: ["What is needed to get below target exposure/ATR?", "Are rents or specials out of step?", "Should price/concession be addressed before advertising?"],
    primary_sources: ["marketing_ops_summary", "unit_feed", "competitor_market_research", "monthly_ad_spend"],
    advisory_sources: ["portfolio_box_score"],
    output_contract: "Recovery math, pricing/concession posture, guardrails, proof.",
    current_directive_setting: "Evaluate pricing, concessions, and spend together before scaling demand.",
    hard_guardrails: ["Competitor value pressure must be considered.", "Pricing claims require source support."],
    do_not_allow_rules: ["Do not recommend spend that ignores value gap or comp pressure."],
    required_evidence: ["exposure/ATR math", "subject rent/special", "competitor posture"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["pricing decision required", "concession conflict", "competitor undercutting"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "word_report", "json_contract"],
  }),
  directive({
    role_id: "signals_officer",
    role_name: "Signals Officer",
    office_type: "consulting_bench",
    plain_role: "Paid media and source efficiency advisor",
    purpose: "Evaluate source output, spend, package efficiency, attribution, channel mix, and cost per result.",
    decision_questions: ["Which sources produce qualified downstream output?", "Is spend helping exposed product?", "Should spend be protected, tightened, shifted, or paused?"],
    primary_sources: ["marketing_bi_source_performance", "monthly_ad_spend", "ga4_traffic_sources"],
    advisory_sources: ["google_ads", "cost_per_conversion"],
    output_contract: "Source-by-source action, budget posture, channel quality read, do-not-scale gate.",
    current_directive_setting: "Activity is not success. Channels earn budget only when downstream output supports recovery.",
    hard_guardrails: ["Downstream output governs channel recommendations."],
    do_not_allow_rules: ["Do not defend spend without downstream output.", "Do not treat support/agency fees as demand channels."],
    required_evidence: ["spend", "source output", "downstream conversion"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["spend increase requested", "channel underproducing", "package value unclear"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "excel_companion", "json_contract"],
  }),
  directive({
    role_id: "navigator",
    role_name: "Navigator",
    office_type: "consulting_bench",
    plain_role: "Website, SEO, GBP, and content advisor",
    purpose: "Evaluate website copy, page structure, SEO/GEO/AEO, GBP, GSC, DataForSEO, local positioning, and exact content changes.",
    decision_questions: ["Does the page support the leasing problem now?", "Are title/meta/H1/copy aligned?", "What exact public copy or GBP angle should be used?"],
    primary_sources: ["ga4_traffic_sources", "gsc_daily", "dataforseo_onpage", "dataforseo_rankings", "gbp_insights", "competitor_market_research"],
    advisory_sources: ["live_page_review", "multifamily_seo_standard"],
    output_contract: "Exact copy/content/metadata/GBP action, reason, proof source.",
    current_directive_setting: "Website and SEO advice must be tied to leasing outcome, not content volume.",
    hard_guardrails: ["No invented local facts.", "Exact recommendations must be evidence-backed."],
    do_not_allow_rules: ["Do not give generic SEO advice.", "Do not keyword dump.", "Do not recommend copy unrelated to leasing condition."],
    required_evidence: ["live/page evidence", "GA4 or GSC context", "content/search source"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["public copy change", "SEO structural issue", "weak local proof"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "word_report", "json_contract"],
  }),
  directive({
    role_id: "market_scout",
    role_name: "Market Scout",
    office_type: "consulting_bench",
    plain_role: "Competitor and market evidence advisor",
    purpose: "Evaluate competitor rents, specials, availability, USPs, packages, reputation, and market pressure.",
    decision_questions: ["Who is cheaper or stronger on specials?", "What do we have that competitors do not?", "Is our offer credible?"],
    primary_sources: ["competitor_market_research", "reputation_com", "unit_feed"],
    advisory_sources: ["dataforseo_business"],
    output_contract: "Subject-vs-comp value read, threats, advantages, capture gaps.",
    current_directive_setting: "Competitor reads require source date, confidence, and comparability.",
    hard_guardrails: ["Comp set comparability must be preserved."],
    do_not_allow_rules: ["Do not make unsourced competitor claims.", "Do not mix non-comparable properties into ordinary comp logic."],
    required_evidence: ["competitor source", "subject rent/special", "capture date"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["competitor undercutting", "conflicting comp evidence", "missing rents"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "word_report", "json_contract"],
  }),
  directive({
    role_id: "product_readiness_officer",
    role_name: "Product Readiness Officer",
    office_type: "consulting_bench",
    plain_role: "Availability, make-ready, and product fit advisor",
    purpose: "Evaluate vacant ready posture, aged units, held units, floorplan pressure, condition/photos, and product-to-demand fit.",
    decision_questions: ["Can the property absorb demand?", "Which products are recovery lane?", "Is demand mismatched to available unit type?"],
    primary_sources: ["unit_feed", "available_unit_interest", "marketing_ops_summary"],
    advisory_sources: ["portfolio_box_score"],
    output_contract: "Readiness read, primary recovery lane, blocker list, proof metric.",
    current_directive_setting: "Total guest-card volume is not enough; demand must match available product.",
    hard_guardrails: ["Unit-type mismatch is a first-class condition."],
    do_not_allow_rules: ["Do not make property-level demand conclusions that ignore unit-type mismatch."],
    required_evidence: ["available units", "available unit interest", "unit/floorplan mix"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["make-ready concern", "unit-type mismatch", "aged/held units"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "word_report", "json_contract"],
  }),
  directive({
    role_id: "reputation_officer",
    role_name: "Reputation Officer",
    office_type: "consulting_bench",
    plain_role: "Trust, review, and sentiment advisor",
    purpose: "Evaluate GBP reviews, Reputation.com, sentiment, complaint themes, response posture, and local reputation competition.",
    decision_questions: ["What public proof helps leasing?", "What themes could scare prospects?", "Is reputation a leasing asset or trust blocker?"],
    primary_sources: ["gbp_reviews", "gbp_reviews_summary", "gbp_review_sentiment", "reputation_com"],
    advisory_sources: ["local_competition"],
    output_contract: "Trust read, praise themes, damage themes, exact action/talk track.",
    current_directive_setting: "Reputation is a conversion lens, not a scorecard.",
    hard_guardrails: ["Complaint themes must be understood before using reputation as proof."],
    do_not_allow_rules: ["Do not publish rating-only reputation reads.", "Do not use positive reputation copy while active complaint themes are unaddressed."],
    required_evidence: ["review volume", "rating/sentiment", "themes"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["negative review pattern", "unanswered reviews", "trust blocker"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "word_report", "json_contract"],
  }),
  directive({
    role_id: "resident_experience_officer",
    role_name: "Resident Experience Officer",
    office_type: "consulting_bench",
    plain_role: "Service, ticket, and resident friction advisor",
    purpose: "Evaluate tickets, no-response risk, reopen rate, service categories, maintenance complaints, and resident friction.",
    decision_questions: ["Is service friction damaging leasing confidence?", "Which issue needs operational closure?"],
    primary_sources: ["reputation_com"],
    advisory_sources: ["service_delivery", "gbp_review_sentiment"],
    output_contract: "Resident friction risk, service themes, operations action, proof source.",
    current_directive_setting: "Resident experience should explain what might hurt conversion or reputation.",
    hard_guardrails: ["Service friction cannot be ignored when it affects public trust."],
    do_not_allow_rules: ["Do not use reputation praise that ignores unresolved service friction."],
    required_evidence: ["resident/service signal", "theme/source"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["service response risk", "repeated maintenance complaint", "public trust risk"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "word_report"],
  }),
  directive({
    role_id: "engineer",
    role_name: "Engineer",
    office_type: "consulting_bench",
    plain_role: "Technical, experience, and validation advisor",
    purpose: "Evaluate PSI/CWV, EVS, BrowserStack, form/CTA path, errors, page speed, and mobile friction.",
    decision_questions: ["Is mobile or technical experience blocking conversion?", "Do forms/CTAs/specials need validation?", "Is a change proven after deployment?"],
    primary_sources: ["pagespeed", "ga4_traffic_sources"],
    advisory_sources: ["evs", "browserstack"],
    output_contract: "Technical blocker read, validation need, proof artifact.",
    current_directive_setting: "Technical health must be presented through conversion relevance.",
    hard_guardrails: ["Raw technical scores are evidence, not a recommendation."],
    do_not_allow_rules: ["Do not publish raw technical scores without leasing impact."],
    required_evidence: ["PSI/CWV", "conversion relevance"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["mobile blocker", "form/CTA failure", "post-change validation missing"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "word_report", "json_contract"],
  }),
  directive({
    role_id: "seasonality_demand_timing_advisor",
    role_name: "Seasonality And Demand Timing Advisor",
    office_type: "consulting_bench",
    plain_role: "Timing, seasonality, and urgency advisor",
    purpose: "Evaluate seasonal demand expectations, leasing window urgency, and month-over-month comparability.",
    decision_questions: ["Is softness seasonal, regional, or property-specific?", "Does urgency match market timing?"],
    primary_sources: ["marketing_ops_summary", "marketing_bi_source_performance"],
    advisory_sources: ["regional_peer_comparisons"],
    output_contract: "Seasonality context, urgency level, comparison caution.",
    current_directive_setting: "Do not overreact to normal seasonality or underreact to a closing leasing window.",
    hard_guardrails: ["Timing context is required for trend interpretation."],
    do_not_allow_rules: ["Do not make trend conclusions without timing context."],
    required_evidence: ["time window", "comparative trend"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["seasonal risk", "leasing window closing", "regional timing pattern"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email"],
  }),
  directive({
    role_id: "unit_type_fit_advisor",
    role_name: "Unit-Type Fit Advisor",
    office_type: "consulting_bench",
    plain_role: "Demand-to-available-product advisor",
    purpose: "Evaluate guest cards per available unit type, PQ by unit type, and exposed floorplan targeting.",
    decision_questions: ["Is demand matching exact available product?", "Which unit type is under-supported?", "Are ads/copy/follow-up aligned to exposed floorplans?"],
    primary_sources: ["available_unit_interest", "unit_feed", "marketing_bi_source_performance"],
    advisory_sources: ["monthly_ad_spend"],
    output_contract: "Unit-type mismatch read, floorplan targeting action, proof metric.",
    current_directive_setting: "A property can have adequate total demand and still have the wrong demand.",
    hard_guardrails: ["Unit-type fit must be considered where available."],
    do_not_allow_rules: ["Do not make total-demand conclusions that ignore unit-type fit."],
    required_evidence: ["unit-type availability", "unit-type demand"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["wrong demand", "floorplan targeting gap", "PQ mismatch"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "word_report", "json_contract"],
  }),
  directive({
    role_id: "market_elasticity_advisor",
    role_name: "Market Elasticity Advisor",
    office_type: "consulting_bench",
    plain_role: "Spend-vs-price response advisor",
    purpose: "Evaluate whether spend can overcome rent, special, or value disadvantage.",
    decision_questions: ["Will more traffic overcome the value gap?", "Are competitors making broad spend inefficient?", "Should price/concession/copy be addressed first?"],
    primary_sources: ["competitor_market_research", "unit_feed"],
    advisory_sources: ["monthly_ad_spend", "marketing_bi_source_performance"],
    output_contract: "Spend-vs-value recommendation, confidence, do-not-scale rule.",
    current_directive_setting: "Spend should not be a reflex when value mismatch is stronger.",
    hard_guardrails: ["Comp/value pressure must be checked before broad scaling."],
    do_not_allow_rules: ["Do not recommend more spend when value mismatch is the stronger constraint."],
    required_evidence: ["subject value", "comp value", "source/spend posture"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["spend-vs-price conflict", "strong comp special", "rent gap"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email"],
  }),
  directive({
    role_id: "operational_capacity_advisor",
    role_name: "Operational Capacity Advisor",
    office_type: "consulting_bench",
    plain_role: "Team capacity and follow-through advisor",
    purpose: "Evaluate whether the team can handle more demand and execute the plan.",
    decision_questions: ["Can the team process more leads without worsening leakage?", "Do open actions have proof and owners?"],
    primary_sources: ["marketing_bi_source_performance"],
    advisory_sources: ["captain_actions", "captain_watch_items", "service_delivery"],
    output_contract: "Capacity/readiness read, follow-through blockers, proof path.",
    current_directive_setting: "Do not add demand to a broken process.",
    hard_guardrails: ["Operational leakage must be addressed before scaling demand."],
    do_not_allow_rules: ["Do not recommend demand increases before operational leakage is addressed."],
    required_evidence: ["funnel output", "action/proof posture"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["follow-up failure", "open action without proof", "process capacity concern"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email"],
  }),
  directive({
    role_id: "trust_and_proof_advisor",
    role_name: "Trust And Proof Advisor",
    office_type: "consulting_bench",
    plain_role: "Claims, proof, and message credibility advisor",
    purpose: "Evaluate whether public claims are supported by reviews, photos, copy, GBP, and resident voice.",
    decision_questions: ["Can the team credibly use this USP?", "Does public evidence support or contradict the claim?", "What proof should be added?"],
    primary_sources: ["gbp_reviews", "gbp_insights", "competitor_market_research", "reputation_com"],
    advisory_sources: ["dataforseo_onpage"],
    output_contract: "Credible claims, proof gaps, message risk.",
    current_directive_setting: "Strong claims require proof.",
    hard_guardrails: ["Public messaging must be proof-safe."],
    do_not_allow_rules: ["Do not publish unsupported USP claims."],
    required_evidence: ["claim", "proof source", "public evidence"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["claim unsupported", "public evidence undermines message", "proof gap"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email", "word_report"],
  }),
  directive({
    role_id: "peer_borrowing_advisor",
    role_name: "Peer Borrowing Advisor",
    office_type: "consulting_bench",
    plain_role: "Regional peer tactics advisor",
    purpose: "Evaluate which stronger sibling properties have tactics that can be borrowed.",
    decision_questions: ["Which regional peer is outperforming on the same constraint?", "What tactic can be borrowed?", "Is this local or regional?"],
    primary_sources: ["marketing_ops_summary", "marketing_bi_source_performance"],
    advisory_sources: ["regional_peer_comparisons", "competitor_market_research"],
    output_contract: "Borrowable peer tactic, peer evidence, regional escalation need.",
    current_directive_setting: "The portfolio is a family; peer advice must be grounded in comparable evidence.",
    hard_guardrails: ["Peer advice requires comparable evidence."],
    do_not_allow_rules: ["Do not make peer recommendations without comparable property evidence."],
    required_evidence: ["peer comparison", "shared constraint", "borrowable tactic"],
    confidence_thresholds: defaultConfidence,
    freshness_tolerance: standardFreshness,
    escalation_triggers: ["regional pattern", "peer tactic candidate", "multi-property issue"],
    publication_permissions: standardPublication,
    external_communication_permissions: internalOnly,
    report_family_applicability: ["captain", "watchlist", "spotlight", "executive_email"],
  }),
];
