import type { OpsWatchSnapshot } from "./types";

// Generated by scripts/build_ops_watch_pond_snapshot.py. Do not edit by hand.
export const OPS_WATCH_SNAPSHOT: OpsWatchSnapshot = {
  "asOf": "2026-09-04T13:55:59Z",
  "captainRecords": [
    {
      "category": "website_media",
      "itemKey": "MKT-14436",
      "itemUrl": "https://venterra.atlassian.net/browse/MKT-14436",
      "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
      "ownerRole": "WebOps / Site Content",
      "priority": "Critical",
      "propertyCode": "GA4AX",
      "propertyName": "Apex West Midtown",
      "severity": "critical",
      "sourceSystem": "jira",
      "staleDays": 8,
      "status": "Pending Vendor",
      "ticketCare": {
        "blockerOwner": "Vendor / owning support lane",
        "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
        "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
        "evidenceNeeded": [
          "Current Jira status and latest customer/vendor comment",
          "Live public-page screenshot or equivalent visual proof"
        ],
        "flagLabels": [
          "Critical",
          "Pending vendor",
          "Vendor idle",
          "Proof needed"
        ],
        "flags": [
          "critical",
          "pending_vendor",
          "vendor_idle",
          "proof_needed"
        ],
        "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "urgencyRank": 178
      },
      "title": "Jira: Update",
      "updated": "2026-08-26T17:46:58.219000Z"
    },
    {
      "category": "vendor_followup",
      "itemKey": "MKT-14482",
      "itemUrl": "https://venterra.atlassian.net/browse/MKT-14482",
      "nextMove": "Chase vendor status, record blocker/proof needed, and close the Captain watch once public readback is clean.",
      "ownerRole": "WebOps / Vendor",
      "priority": "Critical",
      "propertyCode": "TX4BM",
      "propertyName": "Avasa Spring Branch",
      "severity": "critical",
      "sourceSystem": "jira",
      "staleDays": 1,
      "status": "Pending Vendor",
      "ticketCare": {
        "blockerOwner": "Vendor / owning support lane",
        "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
        "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
        "evidenceNeeded": [
          "Current Jira status and latest customer/vendor comment",
          "Correct owner lane and requester expectation"
        ],
        "flagLabels": [
          "Critical",
          "Pending vendor",
          "Routing check"
        ],
        "flags": [
          "critical",
          "pending_vendor",
          "routing_check"
        ],
        "recommendedAction": "Monitor vendor progress and prepare the completion proof path before closing.",
        "urgencyRank": 106
      },
      "title": "Jira: Update Floor Plan Type",
      "updated": "2026-09-02T17:33:01.391000Z"
    },
    {
      "category": "website_media",
      "itemKey": "MKT-13838",
      "itemUrl": "https://venterra.atlassian.net/browse/MKT-13838",
      "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
      "ownerRole": "WebOps / Site Content",
      "priority": "Critical",
      "propertyCode": "GA4CM",
      "propertyName": "Canton Mill Lofts",
      "severity": "critical",
      "sourceSystem": "jira",
      "staleDays": 78,
      "status": "Pending Vendor",
      "ticketCare": {
        "blockerOwner": "Vendor / owning support lane",
        "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
        "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
        "evidenceNeeded": [
          "Current Jira status and latest customer/vendor comment",
          "Live public-page screenshot or equivalent visual proof"
        ],
        "flagLabels": [
          "Critical",
          "Pending vendor",
          "Stale 14+ days",
          "Vendor idle",
          "Proof needed"
        ],
        "flags": [
          "critical",
          "pending_vendor",
          "stale_14_day",
          "vendor_idle",
          "proof_needed"
        ],
        "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "urgencyRank": 260
      },
      "title": "Jira: Canton Mill Lofts - Adding CM Picture to the Website",
      "updated": "2026-06-17T15:23:41.195000Z"
    },
    {
      "category": "website_media",
      "itemKey": "MKT-14024",
      "itemUrl": "https://venterra.atlassian.net/browse/MKT-14024",
      "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
      "ownerRole": "WebOps / Site Content",
      "priority": "Critical",
      "propertyCode": "TX4CL",
      "propertyName": "Preserve at Colony Lakes",
      "severity": "critical",
      "sourceSystem": "jira",
      "staleDays": 84,
      "status": "Pending Vendor",
      "ticketCare": {
        "blockerOwner": "Vendor / owning support lane",
        "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
        "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
        "evidenceNeeded": [
          "Current Jira status and latest customer/vendor comment",
          "Live public-page screenshot or equivalent visual proof"
        ],
        "flagLabels": [
          "Critical",
          "Pending vendor",
          "Stale 14+ days",
          "Vendor idle",
          "Proof needed"
        ],
        "flags": [
          "critical",
          "pending_vendor",
          "stale_14_day",
          "vendor_idle",
          "proof_needed"
        ],
        "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "urgencyRank": 260
      },
      "title": "Jira: Update photo on website",
      "updated": "2026-06-11T18:23:54.190000Z"
    },
    {
      "category": "website_media",
      "itemKey": "MKT-14438",
      "itemUrl": "https://venterra.atlassian.net/browse/MKT-14438",
      "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
      "ownerRole": "WebOps / Site Content",
      "priority": "Critical",
      "propertyCode": "GA4KV",
      "propertyName": "Retreat at Kedron Village",
      "severity": "critical",
      "sourceSystem": "jira",
      "staleDays": 8,
      "status": "Pending Vendor",
      "ticketCare": {
        "blockerOwner": "Vendor / owning support lane",
        "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
        "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
        "evidenceNeeded": [
          "Current Jira status and latest customer/vendor comment",
          "Live public-page screenshot or equivalent visual proof"
        ],
        "flagLabels": [
          "Critical",
          "Pending vendor",
          "Vendor idle",
          "Proof needed",
          "Employee photo"
        ],
        "flags": [
          "critical",
          "pending_vendor",
          "vendor_idle",
          "proof_needed",
          "employee_photo"
        ],
        "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "urgencyRank": 193
      },
      "title": "Jira: Head Shot of Community Manager and MM",
      "updated": "2026-08-26T17:46:56.113000Z"
    },
    {
      "category": "website_media",
      "itemKey": "MKT-13704",
      "itemUrl": "https://venterra.atlassian.net/browse/MKT-13704",
      "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
      "ownerRole": "WebOps / Site Content",
      "priority": "Critical",
      "propertyCode": "TX4GM",
      "propertyName": "The Retreat",
      "severity": "critical",
      "sourceSystem": "jira",
      "staleDays": 31,
      "status": "Response",
      "ticketCare": {
        "blockerOwner": "WebOps / requester follow-up",
        "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
        "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
        "evidenceNeeded": [
          "Current Jira status and latest customer/vendor comment",
          "Live public-page screenshot or equivalent visual proof"
        ],
        "flagLabels": [
          "Critical",
          "Stale 14+ days",
          "Customer waiting",
          "Proof needed"
        ],
        "flags": [
          "critical",
          "stale_14_day",
          "customer_waiting",
          "proof_needed"
        ],
        "recommendedAction": "Answer the requester, confirm the next step, then keep the ticket visible until the customer or workflow closes cleanly.",
        "urgencyRank": 240
      },
      "title": "Jira: Gallery Photos on each floor plan need updating",
      "updated": "2026-08-03T16:46:45.478000Z"
    },
    {
      "category": "website_nap_identity",
      "itemKey": "MKT-14483",
      "itemUrl": "https://venterra.atlassian.net/browse/MKT-14483",
      "nextMove": "Verify the governed property NAP/source value, correct the public surface, and capture before/after proof.",
      "ownerRole": "Navigator / WebOps",
      "priority": "Critical",
      "propertyCode": "MO4TL",
      "propertyName": "Timberlane Village",
      "severity": "critical",
      "sourceSystem": "jira",
      "staleDays": 1,
      "status": "Pending Vendor",
      "ticketCare": {
        "blockerOwner": "Vendor / owning support lane",
        "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
        "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
        "evidenceNeeded": [
          "Current Jira status and latest customer/vendor comment",
          "Live public-page screenshot or equivalent visual proof"
        ],
        "flagLabels": [
          "Critical",
          "Pending vendor",
          "Proof needed"
        ],
        "flags": [
          "critical",
          "pending_vendor",
          "proof_needed"
        ],
        "recommendedAction": "Monitor vendor progress and prepare the completion proof path before closing.",
        "urgencyRank": 116
      },
      "title": "Jira: Google Number Not Working",
      "updated": "2026-09-02T18:15:47.240000Z"
    },
    {
      "category": "website_media",
      "itemKey": "MKT-14439",
      "itemUrl": "https://venterra.atlassian.net/browse/MKT-14439",
      "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
      "ownerRole": "WebOps / Site Content",
      "priority": "Critical",
      "propertyCode": "GA4TU",
      "propertyName": "Tuscany at Lindbergh",
      "severity": "critical",
      "sourceSystem": "jira",
      "staleDays": 8,
      "status": "Pending Vendor",
      "ticketCare": {
        "blockerOwner": "Vendor / owning support lane",
        "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
        "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
        "evidenceNeeded": [
          "Current Jira status and latest customer/vendor comment",
          "Live public-page screenshot or equivalent visual proof"
        ],
        "flagLabels": [
          "Critical",
          "Pending vendor",
          "Vendor idle",
          "Proof needed"
        ],
        "flags": [
          "critical",
          "pending_vendor",
          "vendor_idle",
          "proof_needed"
        ],
        "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "urgencyRank": 178
      },
      "title": "Jira: Please update my picture in the Contact section.",
      "updated": "2026-08-26T17:46:54.148000Z"
    }
  ],
  "commodoreBridge": {
    "escalations": [
      {
        "affectedPropertyCount": 3,
        "captainHrefs": [
          "/captains/TX4CL",
          "/captains/TX4GM",
          "/captains/TX4BM"
        ],
        "escalationKey": "houston-tx-customer-response-is-owed",
        "escalationPath": "Admiral Read candidate",
        "recommendedAction": "Verify the exact requester response needed and prepare a concise response path for the affected Captain.",
        "regionName": "Houston, TX",
        "severity": "critical",
        "title": "Customer response is owed"
      },
      {
        "affectedPropertyCount": 4,
        "captainHrefs": [
          "/captains/GA4CM",
          "/captains/GA4AX",
          "/captains/GA4KV",
          "/captains/GA4TU"
        ],
        "escalationKey": "atlanta-ga-stale-ticket-pressure-needs-owner-review",
        "escalationPath": "Commodore escalation",
        "recommendedAction": "Package stale tickets by owner, ask for ETA or blocker, and escalate if ownership is unclear.",
        "regionName": "Atlanta, GA",
        "severity": "critical",
        "title": "Stale ticket pressure needs owner review"
      }
    ],
    "operatingModel": {
      "actionMode": "Read-only regional intelligence with approval-gated escalation drafts.",
      "boundary": "Commodores do not overwrite Data Pond truth, mutate Jira, or replace Captain property ownership.",
      "owns": "Regional pattern validation, shared lessons, outlier detection, and escalation packaging.",
      "role": "Commodore"
    },
    "patterns": [
      {
        "affectedRegions": [
          "Atlanta, GA",
          "Houston, TX"
        ],
        "escalationPath": "Admiral Read candidate",
        "patternKey": "stale_14_day",
        "propertyCount": 3,
        "recommendedAction": "Package stale items by owner and request a decision or unblocker path.",
        "recordCount": 3,
        "regionCount": 2,
        "severity": "critical",
        "title": "Aging unresolved ticket pressure"
      },
      {
        "affectedRegions": [
          "Houston, TX"
        ],
        "escalationPath": "Admiral Read candidate",
        "patternKey": "customer_waiting",
        "propertyCount": 1,
        "recommendedAction": "Make requester response the immediate next action and keep the Captain flag raised until answered.",
        "recordCount": 1,
        "regionCount": 1,
        "severity": "critical",
        "title": "Customer response owed"
      },
      {
        "affectedRegions": [
          "Atlanta, GA",
          "Houston, TX",
          "Kansas City"
        ],
        "escalationPath": "Commodore Watch",
        "patternKey": "pending_vendor",
        "propertyCount": 7,
        "recommendedAction": "Ask the owning lane for ETA/blocker patterns and escalate repeated idle ownership if it persists.",
        "recordCount": 7,
        "regionCount": 3,
        "severity": "high",
        "title": "Vendor-owned ticket pressure"
      },
      {
        "affectedRegions": [
          "Atlanta, GA"
        ],
        "escalationPath": "Commodore Review",
        "patternKey": "employee_photo",
        "propertyCount": 1,
        "recommendedAction": "Bundle production proof expectations and share the proof-closeout SOP with affected Captains.",
        "recordCount": 1,
        "regionCount": 1,
        "severity": "high",
        "title": "Employee photo / people-image updates"
      },
      {
        "affectedRegions": [
          "Atlanta, GA",
          "Houston, TX",
          "Kansas City"
        ],
        "escalationPath": "Fleet Scribe / Captain SOP",
        "patternKey": "proof_needed",
        "propertyCount": 7,
        "recommendedAction": "Keep proof requirements explicit before any customer-facing closeout.",
        "recordCount": 7,
        "regionCount": 3,
        "severity": "medium",
        "title": "Visible-site proof required"
      },
      {
        "affectedRegions": [
          "Houston, TX"
        ],
        "escalationPath": "Commodore Review",
        "patternKey": "routing_check",
        "propertyCount": 1,
        "recommendedAction": "Confirm correct ownership lane before Captains spend cycles on the wrong action path.",
        "recordCount": 1,
        "regionCount": 1,
        "severity": "medium",
        "title": "Routing-sensitive requests"
      }
    ],
    "regions": [
      {
        "activationStatus": "active",
        "activePropertyCount": 26,
        "activeTicketCount": 3,
        "attentionPropertyCount": 3,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Bayou",
        "commodoreKey": "commodore-bayou",
        "commodoreName": "Commodore Bayou",
        "criticalCount": 3,
        "customerWaitingCount": 1,
        "humanOwner": null,
        "nextBestAction": "Start with TX4CL: MKT-14024: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 2,
        "posture": "blocked",
        "proofNeededCount": 2,
        "properties": [
          {
            "captainHref": "/captains/TX4CL",
            "criticalCount": 1,
            "customerWaitingCount": 0,
            "nextBestAction": "MKT-14024: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
            "pendingVendorCount": 1,
            "posture": "blocked",
            "proofNeededCount": 1,
            "propertyCode": "TX4CL",
            "propertyName": "Preserve at Colony Lakes",
            "records": [
              {
                "category": "website_media",
                "itemKey": "MKT-14024",
                "itemUrl": "https://venterra.atlassian.net/browse/MKT-14024",
                "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
                "ownerRole": "WebOps / Site Content",
                "priority": "Critical",
                "propertyCode": "TX4CL",
                "propertyName": "Preserve at Colony Lakes",
                "severity": "critical",
                "sourceSystem": "jira",
                "staleDays": 84,
                "status": "Pending Vendor",
                "ticketCare": {
                  "blockerOwner": "Vendor / owning support lane",
                  "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
                  "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
                  "evidenceNeeded": [
                    "Current Jira status and latest customer/vendor comment",
                    "Live public-page screenshot or equivalent visual proof"
                  ],
                  "flagLabels": [
                    "Critical",
                    "Pending vendor",
                    "Stale 14+ days",
                    "Vendor idle",
                    "Proof needed"
                  ],
                  "flags": [
                    "critical",
                    "pending_vendor",
                    "stale_14_day",
                    "vendor_idle",
                    "proof_needed"
                  ],
                  "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
                  "urgencyRank": 260
                },
                "title": "Jira: Update photo on website",
                "updated": "2026-06-11T18:23:54.190000Z"
              }
            ],
            "regionName": "Houston, TX",
            "stale14DayCount": 1,
            "ticketCount": 1,
            "topFlag": "stale_14_day"
          },
          {
            "captainHref": "/captains/TX4GM",
            "criticalCount": 1,
            "customerWaitingCount": 1,
            "nextBestAction": "MKT-13704: Answer the requester, confirm the next step, then keep the ticket visible until the customer or workflow closes cleanly.",
            "pendingVendorCount": 0,
            "posture": "blocked",
            "proofNeededCount": 1,
            "propertyCode": "TX4GM",
            "propertyName": "The Retreat",
            "records": [
              {
                "category": "website_media",
                "itemKey": "MKT-13704",
                "itemUrl": "https://venterra.atlassian.net/browse/MKT-13704",
                "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
                "ownerRole": "WebOps / Site Content",
                "priority": "Critical",
                "propertyCode": "TX4GM",
                "propertyName": "The Retreat",
                "severity": "critical",
                "sourceSystem": "jira",
                "staleDays": 31,
                "status": "Response",
                "ticketCare": {
                  "blockerOwner": "WebOps / requester follow-up",
                  "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
                  "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
                  "evidenceNeeded": [
                    "Current Jira status and latest customer/vendor comment",
                    "Live public-page screenshot or equivalent visual proof"
                  ],
                  "flagLabels": [
                    "Critical",
                    "Stale 14+ days",
                    "Customer waiting",
                    "Proof needed"
                  ],
                  "flags": [
                    "critical",
                    "stale_14_day",
                    "customer_waiting",
                    "proof_needed"
                  ],
                  "recommendedAction": "Answer the requester, confirm the next step, then keep the ticket visible until the customer or workflow closes cleanly.",
                  "urgencyRank": 240
                },
                "title": "Jira: Gallery Photos on each floor plan need updating",
                "updated": "2026-08-03T16:46:45.478000Z"
              }
            ],
            "regionName": "Houston, TX",
            "stale14DayCount": 1,
            "ticketCount": 1,
            "topFlag": "customer_waiting"
          },
          {
            "captainHref": "/captains/TX4BM",
            "criticalCount": 1,
            "customerWaitingCount": 0,
            "nextBestAction": "MKT-14482: Monitor vendor progress and prepare the completion proof path before closing.",
            "pendingVendorCount": 1,
            "posture": "warn",
            "proofNeededCount": 0,
            "propertyCode": "TX4BM",
            "propertyName": "Avasa Spring Branch",
            "records": [
              {
                "category": "vendor_followup",
                "itemKey": "MKT-14482",
                "itemUrl": "https://venterra.atlassian.net/browse/MKT-14482",
                "nextMove": "Chase vendor status, record blocker/proof needed, and close the Captain watch once public readback is clean.",
                "ownerRole": "WebOps / Vendor",
                "priority": "Critical",
                "propertyCode": "TX4BM",
                "propertyName": "Avasa Spring Branch",
                "severity": "critical",
                "sourceSystem": "jira",
                "staleDays": 1,
                "status": "Pending Vendor",
                "ticketCare": {
                  "blockerOwner": "Vendor / owning support lane",
                  "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
                  "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
                  "evidenceNeeded": [
                    "Current Jira status and latest customer/vendor comment",
                    "Correct owner lane and requester expectation"
                  ],
                  "flagLabels": [
                    "Critical",
                    "Pending vendor",
                    "Routing check"
                  ],
                  "flags": [
                    "critical",
                    "pending_vendor",
                    "routing_check"
                  ],
                  "recommendedAction": "Monitor vendor progress and prepare the completion proof path before closing.",
                  "urgencyRank": 106
                },
                "title": "Jira: Update Floor Plan Type",
                "updated": "2026-09-02T17:33:01.391000Z"
              }
            ],
            "regionName": "Houston, TX",
            "stale14DayCount": 0,
            "ticketCount": 1,
            "topFlag": "critical"
          }
        ],
        "regionKey": "houston-tx",
        "regionName": "Houston, TX",
        "signaledPropertyCount": 3,
        "stale14DayCount": 2,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "customer_waiting"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 13,
        "activeTicketCount": 4,
        "attentionPropertyCount": 4,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Peachtree",
        "commodoreKey": "commodore-peachtree",
        "commodoreName": "Commodore Peachtree",
        "criticalCount": 4,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "Start with GA4CM: MKT-13838: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 4,
        "posture": "blocked",
        "proofNeededCount": 4,
        "properties": [
          {
            "captainHref": "/captains/GA4CM",
            "criticalCount": 1,
            "customerWaitingCount": 0,
            "nextBestAction": "MKT-13838: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
            "pendingVendorCount": 1,
            "posture": "blocked",
            "proofNeededCount": 1,
            "propertyCode": "GA4CM",
            "propertyName": "Canton Mill Lofts",
            "records": [
              {
                "category": "website_media",
                "itemKey": "MKT-13838",
                "itemUrl": "https://venterra.atlassian.net/browse/MKT-13838",
                "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
                "ownerRole": "WebOps / Site Content",
                "priority": "Critical",
                "propertyCode": "GA4CM",
                "propertyName": "Canton Mill Lofts",
                "severity": "critical",
                "sourceSystem": "jira",
                "staleDays": 78,
                "status": "Pending Vendor",
                "ticketCare": {
                  "blockerOwner": "Vendor / owning support lane",
                  "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
                  "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
                  "evidenceNeeded": [
                    "Current Jira status and latest customer/vendor comment",
                    "Live public-page screenshot or equivalent visual proof"
                  ],
                  "flagLabels": [
                    "Critical",
                    "Pending vendor",
                    "Stale 14+ days",
                    "Vendor idle",
                    "Proof needed"
                  ],
                  "flags": [
                    "critical",
                    "pending_vendor",
                    "stale_14_day",
                    "vendor_idle",
                    "proof_needed"
                  ],
                  "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
                  "urgencyRank": 260
                },
                "title": "Jira: Canton Mill Lofts - Adding CM Picture to the Website",
                "updated": "2026-06-17T15:23:41.195000Z"
              }
            ],
            "regionName": "Atlanta, GA",
            "stale14DayCount": 1,
            "ticketCount": 1,
            "topFlag": "stale_14_day"
          },
          {
            "captainHref": "/captains/GA4AX",
            "criticalCount": 1,
            "customerWaitingCount": 0,
            "nextBestAction": "MKT-14436: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
            "pendingVendorCount": 1,
            "posture": "blocked",
            "proofNeededCount": 1,
            "propertyCode": "GA4AX",
            "propertyName": "Apex West Midtown",
            "records": [
              {
                "category": "website_media",
                "itemKey": "MKT-14436",
                "itemUrl": "https://venterra.atlassian.net/browse/MKT-14436",
                "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
                "ownerRole": "WebOps / Site Content",
                "priority": "Critical",
                "propertyCode": "GA4AX",
                "propertyName": "Apex West Midtown",
                "severity": "critical",
                "sourceSystem": "jira",
                "staleDays": 8,
                "status": "Pending Vendor",
                "ticketCare": {
                  "blockerOwner": "Vendor / owning support lane",
                  "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
                  "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
                  "evidenceNeeded": [
                    "Current Jira status and latest customer/vendor comment",
                    "Live public-page screenshot or equivalent visual proof"
                  ],
                  "flagLabels": [
                    "Critical",
                    "Pending vendor",
                    "Vendor idle",
                    "Proof needed"
                  ],
                  "flags": [
                    "critical",
                    "pending_vendor",
                    "vendor_idle",
                    "proof_needed"
                  ],
                  "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
                  "urgencyRank": 178
                },
                "title": "Jira: Update",
                "updated": "2026-08-26T17:46:58.219000Z"
              }
            ],
            "regionName": "Atlanta, GA",
            "stale14DayCount": 0,
            "ticketCount": 1,
            "topFlag": "vendor_idle"
          },
          {
            "captainHref": "/captains/GA4KV",
            "criticalCount": 1,
            "customerWaitingCount": 0,
            "nextBestAction": "MKT-14438: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
            "pendingVendorCount": 1,
            "posture": "blocked",
            "proofNeededCount": 1,
            "propertyCode": "GA4KV",
            "propertyName": "Retreat at Kedron Village",
            "records": [
              {
                "category": "website_media",
                "itemKey": "MKT-14438",
                "itemUrl": "https://venterra.atlassian.net/browse/MKT-14438",
                "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
                "ownerRole": "WebOps / Site Content",
                "priority": "Critical",
                "propertyCode": "GA4KV",
                "propertyName": "Retreat at Kedron Village",
                "severity": "critical",
                "sourceSystem": "jira",
                "staleDays": 8,
                "status": "Pending Vendor",
                "ticketCare": {
                  "blockerOwner": "Vendor / owning support lane",
                  "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
                  "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
                  "evidenceNeeded": [
                    "Current Jira status and latest customer/vendor comment",
                    "Live public-page screenshot or equivalent visual proof"
                  ],
                  "flagLabels": [
                    "Critical",
                    "Pending vendor",
                    "Vendor idle",
                    "Proof needed",
                    "Employee photo"
                  ],
                  "flags": [
                    "critical",
                    "pending_vendor",
                    "vendor_idle",
                    "proof_needed",
                    "employee_photo"
                  ],
                  "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
                  "urgencyRank": 193
                },
                "title": "Jira: Head Shot of Community Manager and MM",
                "updated": "2026-08-26T17:46:56.113000Z"
              }
            ],
            "regionName": "Atlanta, GA",
            "stale14DayCount": 0,
            "ticketCount": 1,
            "topFlag": "vendor_idle"
          },
          {
            "captainHref": "/captains/GA4TU",
            "criticalCount": 1,
            "customerWaitingCount": 0,
            "nextBestAction": "MKT-14439: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
            "pendingVendorCount": 1,
            "posture": "blocked",
            "proofNeededCount": 1,
            "propertyCode": "GA4TU",
            "propertyName": "Tuscany at Lindbergh",
            "records": [
              {
                "category": "website_media",
                "itemKey": "MKT-14439",
                "itemUrl": "https://venterra.atlassian.net/browse/MKT-14439",
                "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
                "ownerRole": "WebOps / Site Content",
                "priority": "Critical",
                "propertyCode": "GA4TU",
                "propertyName": "Tuscany at Lindbergh",
                "severity": "critical",
                "sourceSystem": "jira",
                "staleDays": 8,
                "status": "Pending Vendor",
                "ticketCare": {
                  "blockerOwner": "Vendor / owning support lane",
                  "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
                  "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
                  "evidenceNeeded": [
                    "Current Jira status and latest customer/vendor comment",
                    "Live public-page screenshot or equivalent visual proof"
                  ],
                  "flagLabels": [
                    "Critical",
                    "Pending vendor",
                    "Vendor idle",
                    "Proof needed"
                  ],
                  "flags": [
                    "critical",
                    "pending_vendor",
                    "vendor_idle",
                    "proof_needed"
                  ],
                  "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
                  "urgencyRank": 178
                },
                "title": "Jira: Please update my picture in the Contact section.",
                "updated": "2026-08-26T17:46:54.148000Z"
              }
            ],
            "regionName": "Atlanta, GA",
            "stale14DayCount": 0,
            "ticketCount": 1,
            "topFlag": "vendor_idle"
          }
        ],
        "regionKey": "atlanta-ga",
        "regionName": "Atlanta, GA",
        "signaledPropertyCount": 4,
        "stale14DayCount": 1,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "stale_14_day"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 1,
        "activeTicketCount": 1,
        "attentionPropertyCount": 1,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Heartland",
        "commodoreKey": "commodore-heartland",
        "commodoreName": "Commodore Heartland",
        "criticalCount": 1,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "Start with MO4TL: MKT-14483: Monitor vendor progress and prepare the completion proof path before closing.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 1,
        "posture": "warn",
        "proofNeededCount": 1,
        "properties": [
          {
            "captainHref": "/captains/MO4TL",
            "criticalCount": 1,
            "customerWaitingCount": 0,
            "nextBestAction": "MKT-14483: Monitor vendor progress and prepare the completion proof path before closing.",
            "pendingVendorCount": 1,
            "posture": "warn",
            "proofNeededCount": 1,
            "propertyCode": "MO4TL",
            "propertyName": "Timberlane Village",
            "records": [
              {
                "category": "website_nap_identity",
                "itemKey": "MKT-14483",
                "itemUrl": "https://venterra.atlassian.net/browse/MKT-14483",
                "nextMove": "Verify the governed property NAP/source value, correct the public surface, and capture before/after proof.",
                "ownerRole": "Navigator / WebOps",
                "priority": "Critical",
                "propertyCode": "MO4TL",
                "propertyName": "Timberlane Village",
                "severity": "critical",
                "sourceSystem": "jira",
                "staleDays": 1,
                "status": "Pending Vendor",
                "ticketCare": {
                  "blockerOwner": "Vendor / owning support lane",
                  "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
                  "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
                  "evidenceNeeded": [
                    "Current Jira status and latest customer/vendor comment",
                    "Live public-page screenshot or equivalent visual proof"
                  ],
                  "flagLabels": [
                    "Critical",
                    "Pending vendor",
                    "Proof needed"
                  ],
                  "flags": [
                    "critical",
                    "pending_vendor",
                    "proof_needed"
                  ],
                  "recommendedAction": "Monitor vendor progress and prepare the completion proof path before closing.",
                  "urgencyRank": 116
                },
                "title": "Jira: Google Number Not Working",
                "updated": "2026-09-02T18:15:47.240000Z"
              }
            ],
            "regionName": "Kansas City",
            "stale14DayCount": 0,
            "ticketCount": 1,
            "topFlag": "critical"
          }
        ],
        "regionKey": "kansas-city",
        "regionName": "Kansas City",
        "signaledPropertyCount": 1,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "pending_vendor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 1,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Marsh",
        "commodoreKey": "commodore-marsh",
        "commodoreName": "Commodore Marsh",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "savannah-ga",
        "regionName": "Savannah, GA",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 7,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Alamo",
        "commodoreKey": "commodore-alamo",
        "commodoreName": "Commodore Alamo",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "san-antonio-tx",
        "regionName": "San Antonio, TX",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 2,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Oak",
        "commodoreKey": "commodore-oak",
        "commodoreName": "Commodore Oak",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "raleigh-nc",
        "regionName": "Raleigh, NC",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 4,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Redbud",
        "commodoreKey": "commodore-redbud",
        "commodoreName": "Commodore Redbud",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "oklahoma",
        "regionName": "Oklahoma",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 1,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Cumberland",
        "commodoreKey": "commodore-cumberland",
        "commodoreName": "Commodore Cumberland",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "nashville-tn",
        "regionName": "Nashville, TN",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 1,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Plum Creek",
        "commodoreKey": "commodore-plum-creek",
        "commodoreName": "Commodore Plum Creek",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "kyle-tx",
        "regionName": "Kyle, TX",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 1,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Crossroads",
        "commodoreKey": "commodore-crossroads",
        "commodoreName": "Commodore Crossroads",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "killeen",
        "regionName": "Killeen",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 6,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Bluegrass",
        "commodoreKey": "commodore-bluegrass",
        "commodoreName": "Commodore Bluegrass",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "kentucky",
        "regionName": "Kentucky",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 19,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Gulf",
        "commodoreKey": "commodore-gulf",
        "commodoreName": "Commodore Gulf",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "florida",
        "regionName": "Florida",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 9,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Trinity",
        "commodoreKey": "commodore-trinity",
        "commodoreName": "Commodore Trinity",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "dallas-tx",
        "regionName": "Dallas, TX",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 1,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Cypress",
        "commodoreKey": "commodore-cypress",
        "commodoreName": "Commodore Cypress",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "cypress-tx",
        "regionName": "Cypress, TX",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 1,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Hill Country",
        "commodoreKey": "commodore-hill-country",
        "commodoreName": "Commodore Hill Country",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "austin-tx",
        "regionName": "Austin, TX",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      },
      {
        "activationStatus": "active",
        "activePropertyCount": 1,
        "activeTicketCount": 0,
        "attentionPropertyCount": 0,
        "cadence": "review_after_each_ops_watch_packet",
        "commodoreCallSign": "Ozark",
        "commodoreKey": "commodore-ozark",
        "commodoreName": "Commodore Ozark",
        "criticalCount": 0,
        "customerWaitingCount": 0,
        "humanOwner": null,
        "nextBestAction": "No mapped Ops Watch ticket pressure is visible for this region.",
        "ordersStatus": "standing_orders_active",
        "pendingVendorCount": 0,
        "posture": "pass",
        "proofNeededCount": 0,
        "properties": [],
        "regionKey": "arkansas",
        "regionName": "Arkansas",
        "signaledPropertyCount": 0,
        "stale14DayCount": 0,
        "standingOrders": [
          "Review regional Captain ticket pressure after each Ops Watch packet.",
          "Identify shared patterns, stalled ownership, proof gaps, and source-readiness blockers across assigned properties.",
          "Route property-specific follow-up back through the owning Captain before escalating.",
          "Package cross-property lessons for Fleet Scribe, Admiral Read, or Ledger review only when evidence supports promotion.",
          "Do not mutate Jira, Confluence, Microsoft 365, Resi content, Cloudflare, Captain Runtime, or Data Pond truth without explicit approval."
        ],
        "topPattern": "monitor"
      }
    ],
    "roster": {
      "authority": "MarketingOps / Property Analytics",
      "cadence": "review_after_each_ops_watch_packet",
      "status": "active",
      "version": "2026-09-04.v1"
    },
    "summary": {
      "activeCommodoreCount": 16,
      "activePropertyCount": 94,
      "activeTicketCount": 8,
      "criticalCount": 8,
      "crossRegionPatternCount": 3,
      "customerWaitingCount": 1,
      "escalationCount": 2,
      "pendingVendorCount": 7,
      "proofNeededCount": 7,
      "regionCount": 16,
      "signaledPropertyCount": 8,
      "stale14DayCount": 3
    }
  },
  "generatedFrom": "reports/ops_watch/ops-watch-20260904-0807/ops-watch-packet.json",
  "governance": {
    "actionMode": "assisted_action_drafts_only",
    "mutationPolicy": "read_only_packet_generation",
    "publishPolicy": "Captain Runtime writes require separate review/approval"
  },
  "readoutPath": "reports/ops_watch/ops-watch-20260904-0807/OPS_WATCH_READOUT.md",
  "runId": "ops-watch-20260904-0807",
  "sourcePackets": [
    {
      "asOf": "2026-09-04T13:55:51Z",
      "runId": "jira-captain-watch-20260904-0807",
      "sourceSystem": "Jira",
      "summary": {
        "captain_record_count": 8,
        "critical_record_count": 8,
        "issue_count": 8,
        "pending_vendor_record_count": 7,
        "property_count": 8,
        "stale_14_day_record_count": 3,
        "unresolved_record_count": 0
      }
    },
    {
      "asOf": "2026-09-04T13:55:51Z",
      "runId": "confluence-ops-watch-20260904-0807",
      "sourceSystem": "Confluence",
      "summary": {
        "captain_record_count": 0,
        "high_severity_signal_count": 6,
        "identity_access_signal_count": 6,
        "page_count": 10,
        "property_count": 0,
        "signal_count": 10
      }
    }
  ],
  "sourceReadiness": [
    {
      "actionBoundary": "Do not edit, comment on, or transition Jira issues unless a later exact rule is approved.",
      "blocker": "",
      "captainVisibility": "property_watch_items_and_actions",
      "credentialSource": "Codex Atlassian Rovo connector",
      "defaultCadence": "weekday_morning",
      "displayName": "Jira assigned ticket queue",
      "harvestMode": "Atlassian connector JQL search, then local Captain packet build",
      "sourceKey": "jira_assigned_queue",
      "status": "active_connector_harvest",
      "system": "Jira"
    },
    {
      "actionBoundary": "Do not comment on or edit Confluence pages unless a later exact rule is approved.",
      "blocker": "",
      "captainVisibility": "documentation_drift_and_decision_watch",
      "credentialSource": "Codex Atlassian Rovo connector",
      "defaultCadence": "daily_or_weekly",
      "displayName": "Confluence operating docs",
      "harvestMode": "Atlassian connector CQL/search, then local Ops Watch evidence packet",
      "sourceKey": "confluence_ops_docs",
      "status": "active_connector_harvest",
      "system": "Confluence"
    },
    {
      "actionBoundary": "Read-only harvest first. Do not send, archive, delete, move, or mark messages without explicit approved rules.",
      "blocker": "Add the Microsoft Graph credential contract to Keeper/KSM before this lane can harvest.",
      "captainVisibility": "email_to_property_watch_items",
      "credentialSource": "Keeper/KSM required",
      "defaultCadence": "weekday_morning_plus_afternoon",
      "displayName": "Outlook mailbox watch",
      "harvestMode": "Microsoft Graph message search from approved mailbox/folders",
      "sourceKey": "ms365_outlook_mailbox",
      "status": "blocked_pending_keeper_graph_auth",
      "system": "Microsoft 365 Outlook"
    },
    {
      "actionBoundary": "Read-only harvest first. Do not post replies, reactions, or notifications without explicit approved rules.",
      "blocker": "Add the Microsoft Graph credential contract to Keeper/KSM before this lane can harvest.",
      "captainVisibility": "teams_to_property_watch_items",
      "credentialSource": "Keeper/KSM required",
      "defaultCadence": "weekday_morning",
      "displayName": "Teams channel and mention watch",
      "harvestMode": "Microsoft Graph channel message and mention read from approved teams/channels",
      "sourceKey": "ms365_teams_channels",
      "status": "blocked_pending_keeper_graph_auth",
      "system": "Microsoft Teams"
    },
    {
      "actionBoundary": "Read-only harvest first. Do not edit, move, delete, or share files without explicit approved rules.",
      "blocker": "Add the Microsoft Graph credential contract to Keeper/KSM before this lane can harvest.",
      "captainVisibility": "new_file_or_evidence_watch",
      "credentialSource": "Keeper/KSM required",
      "defaultCadence": "daily",
      "displayName": "SharePoint and OneDrive evidence watch",
      "harvestMode": "Microsoft Graph drive item delta/list from approved sites and folders",
      "sourceKey": "ms365_sharepoint_onedrive",
      "status": "blocked_pending_keeper_graph_auth",
      "system": "Microsoft 365 SharePoint / OneDrive"
    },
    {
      "actionBoundary": "No D1 write, Cloudflare deploy, or Captain Runtime mutation from harvest jobs unless explicitly approved.",
      "blocker": "Requires reviewed publish approval before mutation.",
      "captainVisibility": "live_captain_office_watch_items_and_actions",
      "credentialSource": "Existing Cloudflare/D1 Keeper-backed helpers",
      "defaultCadence": "after_review",
      "displayName": "Captain Runtime publish",
      "harvestMode": "Reviewed SQL/API publish after local packet review",
      "sourceKey": "captain_runtime_publish",
      "status": "review_required",
      "system": "Captain Runtime"
    }
  ],
  "sourceSignals": [
    {
      "category": "identity_access",
      "nextMove": "Confirm the access owner, approval path, and whether a Jira request or Entra entitlement is the source of truth.",
      "ownerRole": "IT / IAM",
      "severity": "high",
      "signalKey": "conf_5b7bdfdcb056",
      "status": "monitoring",
      "title": "(Draft) - Project Overview: Self-Service Access for Jira & Confluence via Entra Entitlement Management",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/3874947073/Draft+-+Project+Overview+Self-Service+Access+for+Jira+Confluence+via+Entra+Entitlement+Management"
    },
    {
      "category": "identity_access",
      "nextMove": "Confirm the access owner, approval path, and whether a Jira request or Entra entitlement is the source of truth.",
      "ownerRole": "IT / IAM",
      "severity": "high",
      "signalKey": "conf_b8067134ad05",
      "status": "monitoring",
      "title": "Draft 2 - IAM Strategy",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/4078829573/Draft+2+-+IAM+Strategy"
    },
    {
      "category": "identity_access",
      "nextMove": "Confirm the access owner, approval path, and whether a Jira request or Entra entitlement is the source of truth.",
      "ownerRole": "IT / IAM",
      "severity": "high",
      "signalKey": "conf_3e7d1f2ba4ad",
      "status": "monitoring",
      "title": "Engineering - TicketSync: Teams Transcript -> SharePoint Access",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/4304502786/Engineering+TicketSync+Teams+Transcript+SharePoint+Access"
    },
    {
      "category": "identity_access",
      "nextMove": "Confirm the access owner, approval path, and whether a Jira request or Entra entitlement is the source of truth.",
      "ownerRole": "IT / IAM",
      "severity": "high",
      "signalKey": "conf_e55ccd8750cc",
      "status": "monitoring",
      "title": "PROC - Support Process Step 2 > Trouble Shooting (Tier 1)",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/3816980481/PROC+-+Support+Process+Step+2+Trouble+Shooting+Tier+1"
    },
    {
      "category": "identity_access",
      "nextMove": "Confirm the access owner, approval path, and whether a Jira request or Entra entitlement is the source of truth.",
      "ownerRole": "IT / IAM",
      "severity": "high",
      "signalKey": "conf_4b769078f235",
      "status": "monitoring",
      "title": "PROC - Support Process Step 3E > IAM (Login / Access / SSO) (Tier 1 / IT Support)",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/4253483009/PROC+-+Support+Process+Step+3E+IAM+Login+Access+SSO+Tier+1+IT+Support"
    },
    {
      "category": "identity_access",
      "nextMove": "Confirm the access owner, approval path, and whether a Jira request or Entra entitlement is the source of truth.",
      "ownerRole": "IT / IAM",
      "severity": "high",
      "signalKey": "conf_1d1e49b3ccff",
      "status": "monitoring",
      "title": "Proc: Deploy and Maintain Microsoft 365 Copilot Confluence Connector",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/3490283523/Proc+Deploy+and+Maintain+Microsoft+365+Copilot+Confluence+Connector"
    },
    {
      "category": "microsoft_365",
      "nextMove": "Confirm the operating owner and capture the approved integration or support path before automation uses the lane.",
      "ownerRole": "IT / Collaboration Systems",
      "severity": "medium",
      "signalKey": "conf_b87cfa28fd2c",
      "status": "monitoring",
      "title": "Jira Service Management (ITSM) Structure Proposal",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/3786080264/Jira+Service+Management+ITSM+Structure+Proposal"
    },
    {
      "category": "microsoft_365",
      "nextMove": "Confirm the operating owner and capture the approved integration or support path before automation uses the lane.",
      "ownerRole": "IT / Collaboration Systems",
      "severity": "medium",
      "signalKey": "conf_ed3349e3c0ac",
      "status": "monitoring",
      "title": "Jira Service Management ITSM Structure Proposal for Improved Ticket Routing and User Experience",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/3742072852/Jira+Service+Management+ITSM+Structure+Proposal+for+Improved+Ticket+Routing+and+User+Experience"
    },
    {
      "category": "microsoft_365",
      "nextMove": "Confirm the operating owner and capture the approved integration or support path before automation uses the lane.",
      "ownerRole": "IT / Collaboration Systems",
      "severity": "medium",
      "signalKey": "conf_2831dea23f4b",
      "status": "monitoring",
      "title": "PROC - Support Process Step 3D > Microsoft 365 (Email / Teams / SharePoint) (Tier 1 / IT Support)",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/4251484209/PROC+-+Support+Process+Step+3D+Microsoft+365+Email+Teams+SharePoint+Tier+1+IT+Support"
    },
    {
      "category": "microsoft_365",
      "nextMove": "Confirm the operating owner and capture the approved integration or support path before automation uses the lane.",
      "ownerRole": "IT / Collaboration Systems",
      "severity": "medium",
      "signalKey": "conf_7a3ee4448f34",
      "status": "monitoring",
      "title": "Proc: Deploy and Maintain Microsoft 365 Copilot Jira Connector",
      "updated": null,
      "url": "https://venterra.atlassian.net/wiki/spaces/ITSM/pages/3756556296/Proc+Deploy+and+Maintain+Microsoft+365+Copilot+Jira+Connector"
    }
  ],
  "summary": {
    "active_source_count": 2,
    "blocked_source_count": 3,
    "captain_record_count": 8,
    "confluence_packet_count": 1,
    "connector_ready_not_harvested_count": 0,
    "critical_record_count": 8,
    "high_source_signal_count": 6,
    "jira_packet_count": 1,
    "pending_vendor_record_count": 7,
    "property_count": 8,
    "source_count": 6,
    "source_signal_count": 10,
    "stale_14_day_record_count": 3,
    "unresolved_record_count": 0
  },
  "ticketCare": {
    "patterns": [
      {
        "patternKey": "employee_photo",
        "propertyCount": 1,
        "recommendedAction": "Bundle related photo tickets, watch the production image move, and close only after visual proof is attached.",
        "recordCount": 1,
        "title": "Employee photo updates"
      },
      {
        "patternKey": "pending_vendor",
        "propertyCount": 7,
        "recommendedAction": "Use concise status inquiries and keep Captains aware until the owning lane responds.",
        "recordCount": 7,
        "title": "Pending vendor follow-up"
      },
      {
        "patternKey": "stale_14_day",
        "propertyCount": 3,
        "recommendedAction": "Escalate or re-check owner status before letting property concerns age silently.",
        "recordCount": 3,
        "title": "Stale tickets"
      },
      {
        "patternKey": "proof_needed",
        "propertyCount": 7,
        "recommendedAction": "Follow the image-only reply plus closure-comment SOP for visible website changes.",
        "recordCount": 7,
        "title": "Proof-based closeout"
      },
      {
        "patternKey": "routing_check",
        "propertyCount": 1,
        "recommendedAction": "Confirm whether the ticket belongs in WebOps or a pricing/content-system lane.",
        "recordCount": 1,
        "title": "Routing checks"
      }
    ],
    "propertyQueues": [
      {
        "customerWaitingCount": 0,
        "nextBestAction": "MKT-14436: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "pendingVendorCount": 1,
        "posture": "blocked",
        "proofNeededCount": 1,
        "propertyCode": "GA4AX",
        "propertyName": "Apex West Midtown",
        "records": [
          {
            "category": "website_media",
            "itemKey": "MKT-14436",
            "itemUrl": "https://venterra.atlassian.net/browse/MKT-14436",
            "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
            "ownerRole": "WebOps / Site Content",
            "priority": "Critical",
            "propertyCode": "GA4AX",
            "propertyName": "Apex West Midtown",
            "severity": "critical",
            "sourceSystem": "jira",
            "staleDays": 8,
            "status": "Pending Vendor",
            "ticketCare": {
              "blockerOwner": "Vendor / owning support lane",
              "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
              "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
              "evidenceNeeded": [
                "Current Jira status and latest customer/vendor comment",
                "Live public-page screenshot or equivalent visual proof"
              ],
              "flagLabels": [
                "Critical",
                "Pending vendor",
                "Vendor idle",
                "Proof needed"
              ],
              "flags": [
                "critical",
                "pending_vendor",
                "vendor_idle",
                "proof_needed"
              ],
              "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
              "urgencyRank": 178
            },
            "title": "Jira: Update",
            "updated": "2026-08-26T17:46:58.219000Z"
          }
        ],
        "staleCount": 0,
        "ticketCount": 1,
        "topFlag": "vendor_idle"
      },
      {
        "customerWaitingCount": 0,
        "nextBestAction": "MKT-13838: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "pendingVendorCount": 1,
        "posture": "blocked",
        "proofNeededCount": 1,
        "propertyCode": "GA4CM",
        "propertyName": "Canton Mill Lofts",
        "records": [
          {
            "category": "website_media",
            "itemKey": "MKT-13838",
            "itemUrl": "https://venterra.atlassian.net/browse/MKT-13838",
            "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
            "ownerRole": "WebOps / Site Content",
            "priority": "Critical",
            "propertyCode": "GA4CM",
            "propertyName": "Canton Mill Lofts",
            "severity": "critical",
            "sourceSystem": "jira",
            "staleDays": 78,
            "status": "Pending Vendor",
            "ticketCare": {
              "blockerOwner": "Vendor / owning support lane",
              "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
              "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
              "evidenceNeeded": [
                "Current Jira status and latest customer/vendor comment",
                "Live public-page screenshot or equivalent visual proof"
              ],
              "flagLabels": [
                "Critical",
                "Pending vendor",
                "Stale 14+ days",
                "Vendor idle",
                "Proof needed"
              ],
              "flags": [
                "critical",
                "pending_vendor",
                "stale_14_day",
                "vendor_idle",
                "proof_needed"
              ],
              "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
              "urgencyRank": 260
            },
            "title": "Jira: Canton Mill Lofts - Adding CM Picture to the Website",
            "updated": "2026-06-17T15:23:41.195000Z"
          }
        ],
        "staleCount": 1,
        "ticketCount": 1,
        "topFlag": "stale_14_day"
      },
      {
        "customerWaitingCount": 0,
        "nextBestAction": "MKT-14438: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "pendingVendorCount": 1,
        "posture": "blocked",
        "proofNeededCount": 1,
        "propertyCode": "GA4KV",
        "propertyName": "Retreat at Kedron Village",
        "records": [
          {
            "category": "website_media",
            "itemKey": "MKT-14438",
            "itemUrl": "https://venterra.atlassian.net/browse/MKT-14438",
            "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
            "ownerRole": "WebOps / Site Content",
            "priority": "Critical",
            "propertyCode": "GA4KV",
            "propertyName": "Retreat at Kedron Village",
            "severity": "critical",
            "sourceSystem": "jira",
            "staleDays": 8,
            "status": "Pending Vendor",
            "ticketCare": {
              "blockerOwner": "Vendor / owning support lane",
              "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
              "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
              "evidenceNeeded": [
                "Current Jira status and latest customer/vendor comment",
                "Live public-page screenshot or equivalent visual proof"
              ],
              "flagLabels": [
                "Critical",
                "Pending vendor",
                "Vendor idle",
                "Proof needed",
                "Employee photo"
              ],
              "flags": [
                "critical",
                "pending_vendor",
                "vendor_idle",
                "proof_needed",
                "employee_photo"
              ],
              "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
              "urgencyRank": 193
            },
            "title": "Jira: Head Shot of Community Manager and MM",
            "updated": "2026-08-26T17:46:56.113000Z"
          }
        ],
        "staleCount": 0,
        "ticketCount": 1,
        "topFlag": "vendor_idle"
      },
      {
        "customerWaitingCount": 0,
        "nextBestAction": "MKT-14439: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "pendingVendorCount": 1,
        "posture": "blocked",
        "proofNeededCount": 1,
        "propertyCode": "GA4TU",
        "propertyName": "Tuscany at Lindbergh",
        "records": [
          {
            "category": "website_media",
            "itemKey": "MKT-14439",
            "itemUrl": "https://venterra.atlassian.net/browse/MKT-14439",
            "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
            "ownerRole": "WebOps / Site Content",
            "priority": "Critical",
            "propertyCode": "GA4TU",
            "propertyName": "Tuscany at Lindbergh",
            "severity": "critical",
            "sourceSystem": "jira",
            "staleDays": 8,
            "status": "Pending Vendor",
            "ticketCare": {
              "blockerOwner": "Vendor / owning support lane",
              "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
              "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
              "evidenceNeeded": [
                "Current Jira status and latest customer/vendor comment",
                "Live public-page screenshot or equivalent visual proof"
              ],
              "flagLabels": [
                "Critical",
                "Pending vendor",
                "Vendor idle",
                "Proof needed"
              ],
              "flags": [
                "critical",
                "pending_vendor",
                "vendor_idle",
                "proof_needed"
              ],
              "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
              "urgencyRank": 178
            },
            "title": "Jira: Please update my picture in the Contact section.",
            "updated": "2026-08-26T17:46:54.148000Z"
          }
        ],
        "staleCount": 0,
        "ticketCount": 1,
        "topFlag": "vendor_idle"
      },
      {
        "customerWaitingCount": 0,
        "nextBestAction": "MKT-14483: Monitor vendor progress and prepare the completion proof path before closing.",
        "pendingVendorCount": 1,
        "posture": "warn",
        "proofNeededCount": 1,
        "propertyCode": "MO4TL",
        "propertyName": "Timberlane Village",
        "records": [
          {
            "category": "website_nap_identity",
            "itemKey": "MKT-14483",
            "itemUrl": "https://venterra.atlassian.net/browse/MKT-14483",
            "nextMove": "Verify the governed property NAP/source value, correct the public surface, and capture before/after proof.",
            "ownerRole": "Navigator / WebOps",
            "priority": "Critical",
            "propertyCode": "MO4TL",
            "propertyName": "Timberlane Village",
            "severity": "critical",
            "sourceSystem": "jira",
            "staleDays": 1,
            "status": "Pending Vendor",
            "ticketCare": {
              "blockerOwner": "Vendor / owning support lane",
              "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
              "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
              "evidenceNeeded": [
                "Current Jira status and latest customer/vendor comment",
                "Live public-page screenshot or equivalent visual proof"
              ],
              "flagLabels": [
                "Critical",
                "Pending vendor",
                "Proof needed"
              ],
              "flags": [
                "critical",
                "pending_vendor",
                "proof_needed"
              ],
              "recommendedAction": "Monitor vendor progress and prepare the completion proof path before closing.",
              "urgencyRank": 116
            },
            "title": "Jira: Google Number Not Working",
            "updated": "2026-09-02T18:15:47.240000Z"
          }
        ],
        "staleCount": 0,
        "ticketCount": 1,
        "topFlag": "critical"
      },
      {
        "customerWaitingCount": 0,
        "nextBestAction": "MKT-14482: Monitor vendor progress and prepare the completion proof path before closing.",
        "pendingVendorCount": 1,
        "posture": "warn",
        "proofNeededCount": 0,
        "propertyCode": "TX4BM",
        "propertyName": "Avasa Spring Branch",
        "records": [
          {
            "category": "vendor_followup",
            "itemKey": "MKT-14482",
            "itemUrl": "https://venterra.atlassian.net/browse/MKT-14482",
            "nextMove": "Chase vendor status, record blocker/proof needed, and close the Captain watch once public readback is clean.",
            "ownerRole": "WebOps / Vendor",
            "priority": "Critical",
            "propertyCode": "TX4BM",
            "propertyName": "Avasa Spring Branch",
            "severity": "critical",
            "sourceSystem": "jira",
            "staleDays": 1,
            "status": "Pending Vendor",
            "ticketCare": {
              "blockerOwner": "Vendor / owning support lane",
              "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
              "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
              "evidenceNeeded": [
                "Current Jira status and latest customer/vendor comment",
                "Correct owner lane and requester expectation"
              ],
              "flagLabels": [
                "Critical",
                "Pending vendor",
                "Routing check"
              ],
              "flags": [
                "critical",
                "pending_vendor",
                "routing_check"
              ],
              "recommendedAction": "Monitor vendor progress and prepare the completion proof path before closing.",
              "urgencyRank": 106
            },
            "title": "Jira: Update Floor Plan Type",
            "updated": "2026-09-02T17:33:01.391000Z"
          }
        ],
        "staleCount": 0,
        "ticketCount": 1,
        "topFlag": "critical"
      },
      {
        "customerWaitingCount": 0,
        "nextBestAction": "MKT-14024: Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
        "pendingVendorCount": 1,
        "posture": "blocked",
        "proofNeededCount": 1,
        "propertyCode": "TX4CL",
        "propertyName": "Preserve at Colony Lakes",
        "records": [
          {
            "category": "website_media",
            "itemKey": "MKT-14024",
            "itemUrl": "https://venterra.atlassian.net/browse/MKT-14024",
            "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
            "ownerRole": "WebOps / Site Content",
            "priority": "Critical",
            "propertyCode": "TX4CL",
            "propertyName": "Preserve at Colony Lakes",
            "severity": "critical",
            "sourceSystem": "jira",
            "staleDays": 84,
            "status": "Pending Vendor",
            "ticketCare": {
              "blockerOwner": "Vendor / owning support lane",
              "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
              "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
              "evidenceNeeded": [
                "Current Jira status and latest customer/vendor comment",
                "Live public-page screenshot or equivalent visual proof"
              ],
              "flagLabels": [
                "Critical",
                "Pending vendor",
                "Stale 14+ days",
                "Vendor idle",
                "Proof needed"
              ],
              "flags": [
                "critical",
                "pending_vendor",
                "stale_14_day",
                "vendor_idle",
                "proof_needed"
              ],
              "recommendedAction": "Post a concise status inquiry, ask for ETA or blocker, and keep the Captain flag raised until a response or proof arrives.",
              "urgencyRank": 260
            },
            "title": "Jira: Update photo on website",
            "updated": "2026-06-11T18:23:54.190000Z"
          }
        ],
        "staleCount": 1,
        "ticketCount": 1,
        "topFlag": "stale_14_day"
      },
      {
        "customerWaitingCount": 1,
        "nextBestAction": "MKT-13704: Answer the requester, confirm the next step, then keep the ticket visible until the customer or workflow closes cleanly.",
        "pendingVendorCount": 0,
        "posture": "blocked",
        "proofNeededCount": 1,
        "propertyCode": "TX4GM",
        "propertyName": "The Retreat",
        "records": [
          {
            "category": "website_media",
            "itemKey": "MKT-13704",
            "itemUrl": "https://venterra.atlassian.net/browse/MKT-13704",
            "nextMove": "Identify the exact image/location, coordinate vendor or content-system change, and attach visual readback proof after update.",
            "ownerRole": "WebOps / Site Content",
            "priority": "Critical",
            "propertyCode": "TX4GM",
            "propertyName": "The Retreat",
            "severity": "critical",
            "sourceSystem": "jira",
            "staleDays": 31,
            "status": "Response",
            "ticketCare": {
              "blockerOwner": "WebOps / requester follow-up",
              "captainStance": "Champion the property by keeping this ticket visible until the owner, proof, or requester response clears the concern.",
              "customerPromise": "Keep the requester informed without promising completion until source proof exists.",
              "evidenceNeeded": [
                "Current Jira status and latest customer/vendor comment",
                "Live public-page screenshot or equivalent visual proof"
              ],
              "flagLabels": [
                "Critical",
                "Stale 14+ days",
                "Customer waiting",
                "Proof needed"
              ],
              "flags": [
                "critical",
                "stale_14_day",
                "customer_waiting",
                "proof_needed"
              ],
              "recommendedAction": "Answer the requester, confirm the next step, then keep the ticket visible until the customer or workflow closes cleanly.",
              "urgencyRank": 240
            },
            "title": "Jira: Gallery Photos on each floor plan need updating",
            "updated": "2026-08-03T16:46:45.478000Z"
          }
        ],
        "staleCount": 1,
        "ticketCount": 1,
        "topFlag": "customer_waiting"
      }
    ],
    "summary": {
      "criticalCount": 8,
      "customerWaitingCount": 1,
      "employeePhotoCount": 1,
      "pendingVendorCount": 7,
      "proofNeededCount": 7,
      "propertyCount": 8,
      "routingCheckCount": 1,
      "stale14DayCount": 3,
      "ticketCount": 8,
      "vendorIdleCount": 5
    }
  }
};
