import type { Env } from "../../src/env";

export function createPlatformRouteEnv(db: D1Database): Env {
  return {
    POP_BRIEF_DB: db,
    POP_BRIEF_UPLOADS: {} as R2Bucket,
    RESI_EDGE_ASSETS: {} as R2Bucket,
    RESEND_API_KEY: "test-resend",
    EMAIL_FROM: "test@example.com",
    SEMRUSH_API_KEY: "test-semrush",
    SESSION_SIGNING_SECRET: "test-secret",
    ENABLE_EMAIL_SEND: "false",
    OPENAI_API_KEY: "test-openai",
    PLATFORM_SHARED_TOKEN: "test-platform-token",
    PLATFORM_ACCESS_CLIENT_ID: "test-platform-client-id",
    PLATFORM_ACCESS_CLIENT_SECRET: "test-platform-client-secret",
    VACS_ACCESS_CLIENT_ID: "test-vacs-client-id",
    VACS_ACCESS_CLIENT_SECRET: "test-vacs-client-secret",
    EVS_SHARED_TOKEN: "test-evs-token",
    EVS_ACCESS_CLIENT_ID: "test-evs-client-id",
    EVS_ACCESS_CLIENT_SECRET: "test-evs-client-secret",
    CLOUDFLARE_ACCESS_TEAM_DOMAIN: "https://macxs.cloudflareaccess.com",
    MODEL_GATEWAY_ENABLED: "false",
    MODEL_GATEWAY_ALLOW_LIVE_CALLS: "false",
    MODEL_GATEWAY_PROVIDER_SHADOW_ENABLED: "false",
    MODEL_GATEWAY_PROVIDER_LIVE_ENABLED: "false",
    MODEL_GATEWAY_DEFAULT_ADAPTER: "deterministic",
    MODEL_GATEWAY_ACCEPTED_OUTPUT_ADAPTER: "deterministic",
    MODEL_GATEWAY_SHADOW_PROVIDER_ADAPTER: "cloudflare_ai_gateway",
    MODEL_GATEWAY_KILL_SWITCH: "true",
    MODEL_GATEWAY_SHADOW_MODE: "false",
    MODEL_GATEWAY_DRY_RUN: "true",
    MODEL_GATEWAY_STORE_REDACTED_PAYLOAD: "true",
    MODEL_GATEWAY_STORE_RAW_PAYLOAD: "false",
    CLOUDFLARE_AI_GATEWAY_ENABLED: "false",
    CLOUDFLARE_AI_GATEWAY_REQUIRE_AUTH: "true",
  };
}
