name = "edge-transparent-pricing-intro-beta"
main = "worker.js"
compatibility_date = "2024-12-01"
workers_dev = false

routes = [
  { pattern = "pilot.venterradev.com/*", zone_name = "venterradev.com" }
]

[[d1_databases]]
binding = "POP_BRIEF_DB"
database_name = "pop-brief-db"
database_id = "dad3e7d1-147b-438d-8cd0-2cbf537a87b2"
