-- Migration 028: Marketing Ops Summary workbook
-- Property-level operating, traffic, pricing, financial, and Kingsley summary rows.

CREATE TABLE IF NOT EXISTS marketing_ops_summary_rows (
  id TEXT PRIMARY KEY,
  report_date TEXT NOT NULL,
  source_as_of_date TEXT,
  region TEXT,
  property_name TEXT NOT NULL,
  property_id TEXT,
  community_id TEXT,
  units INTEGER,
  occupancy REAL,
  atr30 REAL,
  atr REAL,
  leads_t30_py INTEGER,
  leads_t30 INTEGER,
  leads_t30_var REAL,
  leads_t7_py INTEGER,
  leads_t7 INTEGER,
  leads_t7_var REAL,
  leads_trend REAL,
  lead_to_visit_t30 REAL,
  lead_to_visit_t7 REAL,
  visits_t30_py INTEGER,
  visits_t30 INTEGER,
  visits_t30_var REAL,
  visits_t7_py INTEGER,
  visits_t7 INTEGER,
  visits_t7_var REAL,
  visits_trend REAL,
  leases_t7_py INTEGER,
  leases_t7 INTEGER,
  traffic_per_unit REAL,
  benchmark_t30_pf REAL,
  benchmark_rank INTEGER,
  benchmark_var REAL,
  close_ratio REAL,
  projected_traffic REAL,
  projected_traffic_gap REAL,
  current_month_expirations INTEGER,
  forward_3_month_expirations INTEGER,
  forward_3_month_expirations_pct REAL,
  expirations_var REAL,
  new_lease_tradeoff_dollars REAL,
  new_lease_tradeoff_pct REAL,
  renewal_tradeoff_dollars REAL,
  renewal_tradeoff_pct REAL,
  offered_vs_book REAL,
  offered_60d_delta REAL,
  offered_30d_delta REAL,
  offered_7d_delta REAL,
  ad_spend_t3_property REAL,
  ad_spend_t3_portfolio REAL,
  ad_spend_rank INTEGER,
  ad_spend_var REAL,
  ad_spend_t1_budget REAL,
  ad_spend_t1_actual REAL,
  ad_spend_t1_var REAL,
  ad_spend_t3_budget REAL,
  ad_spend_t3_actual REAL,
  ad_spend_t3_var REAL,
  ad_spend_t1_vs_t3 REAL,
  ad_spend_t3_vs_t6 REAL,
  kingsley_find_property_avg_t7 REAL,
  kingsley_find_property_avg_t30 REAL,
  kingsley_find_property_py_avg_t30 REAL,
  kingsley_deposit_yes_pct_t7 REAL,
  kingsley_deposit_yes_pct_t30 REAL,
  kingsley_tour_yes_pct_t7 REAL,
  kingsley_tour_yes_pct_t30 REAL,
  source_file TEXT NOT NULL,
  evidence_json TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(report_date, property_name, source_file)
);

CREATE INDEX IF NOT EXISTS idx_marketing_ops_summary_property_date
  ON marketing_ops_summary_rows(property_id, report_date DESC);

CREATE INDEX IF NOT EXISTS idx_marketing_ops_summary_region_date
  ON marketing_ops_summary_rows(region, report_date DESC);
